version: 0.2
           
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install mkdocs
  build:
    commands:
      - cd usm-engineering-principles
      - mkdocs build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: usm-engineering-principles/site